/*
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
import {
  mkdir, writeFile, chmod, access,
} from 'node:fs/promises';
import { constants as fsConstants } from 'node:fs';
import { join, delimiter } from 'node:path';
import { homedir } from 'node:os';

/**
 * Installs a small `content` launcher on the user's PATH. The launcher runs the
 * bundled Electron binary in Node mode (`ELECTRON_RUN_AS_NODE`) against the CLI
 * entry script, so it needs no system Node install and shares the app's stored
 * sites/tokens via `AEM_DESKTOP_USER_DATA`.
 */

/**
 * Quotes a value for safe inclusion inside a double-quoted POSIX shell string.
 *
 * @param {string} value
 * @returns {string}
 */
export function shellQuote(value) {
  return `"${String(value).replace(/(["\\$`])/g, '\\$1')}"`;
}

/**
 * Builds the POSIX (`/bin/sh`) launcher script.
 *
 * @param {{ execPath: string, cliEntry: string, userData: string }} options
 * @returns {string}
 */
export function buildLauncherScript({ execPath, cliEntry, userData }) {
  return `${[
    '#!/bin/sh',
    '# AEM Desktop "content" CLI launcher — generated by "Install CLI".',
    '# Runs the bundled Electron binary as Node against the CLI entry script.',
    `exec env AEM_DESKTOP_USER_DATA=${shellQuote(userData)} ELECTRON_RUN_AS_NODE=1 `
      + `${shellQuote(execPath)} ${shellQuote(cliEntry)} "$@"`,
  ].join('\n')}\n`;
}

/**
 * Builds the Windows (`content.cmd`) launcher script.
 *
 * @param {{ execPath: string, cliEntry: string, userData: string }} options
 * @returns {string}
 */
export function buildWindowsLauncher({ execPath, cliEntry, userData }) {
  return `${[
    '@echo off',
    'rem AEM Desktop "content" CLI launcher — generated by "Install CLI".',
    `set "AEM_DESKTOP_USER_DATA=${userData}"`,
    'set "ELECTRON_RUN_AS_NODE=1"',
    `"${execPath}" "${cliEntry}" %*`,
  ].join('\r\n')}\r\n`;
}

/**
 * Whether `dir` appears as an entry in a PATH-style string.
 *
 * @param {string} dir
 * @param {string|undefined} pathEnv
 * @returns {boolean}
 */
export function isOnPath(dir, pathEnv) {
  if (!pathEnv) {
    return false;
  }
  return pathEnv.split(delimiter).map((p) => p.replace(/[/\\]+$/, '')).includes(
    dir.replace(/[/\\]+$/, ''),
  );
}

/**
 * @param {string} dir
 * @returns {Promise<boolean>}
 */
async function isWritableDir(dir) {
  try {
    await access(dir, fsConstants.W_OK);
    return true;
  } catch {
    return false;
  }
}

/**
 * Picks the install directory: the system bin dir when it is writable (already
 * on PATH for most shells), otherwise a user-owned `~/.local/bin` we can always
 * create. Windows uses a per-user programs dir.
 *
 * @param {{ platform: string, home: string, systemBinDir: string }} ctx
 * @returns {Promise<string>}
 */
async function chooseBinDir({ platform, home, systemBinDir }) {
  if (platform === 'win32') {
    return join(home, 'AppData', 'Local', 'AEM Desktop', 'bin');
  }
  if (await isWritableDir(systemBinDir)) {
    return systemBinDir;
  }
  return join(home, '.local', 'bin');
}

/**
 * Writes the launcher and reports where it landed and whether that directory is
 * on PATH (so the caller can tell the user to add it if not).
 *
 * @param {{
 *   execPath: string,
 *   cliEntry: string,
 *   userData: string,
 *   platform?: string,
 *   home?: string,
 *   pathEnv?: string,
 *   systemBinDir?: string,
 * }} options
 * @returns {Promise<{ path: string, dir: string, onPath: boolean }>}
 */
export async function installCli({
  execPath,
  cliEntry,
  userData,
  platform = process.platform,
  home = homedir(),
  pathEnv = process.env.PATH,
  systemBinDir = '/usr/local/bin',
}) {
  const dir = await chooseBinDir({ platform, home, systemBinDir });
  await mkdir(dir, { recursive: true });

  if (platform === 'win32') {
    const target = join(dir, 'content.cmd');
    await writeFile(target, buildWindowsLauncher({ execPath, cliEntry, userData }), 'utf8');
    return { path: target, dir, onPath: isOnPath(dir, pathEnv) };
  }

  const target = join(dir, 'content');
  await writeFile(target, buildLauncherScript({ execPath, cliEntry, userData }), 'utf8');
  await chmod(target, 0o755);
  return { path: target, dir, onPath: isOnPath(dir, pathEnv) };
}
